### ISSUE TITLE
Multiple markers with the same latitude & longitude

### ISSUE THREAD

**Issue by BramDC3** [johnpryan/flutter_map#100]
I'm working on a Flutter app that has a list of learning opportunities that can happen on the same location, but right now the markers on the map just stack. I don't think there's a way yet to display the number of markers that overlap.

**Comment by johnpryan** [comment]
Not out of the box, but you can manually "cluster" the pins on the client side or cluster them some other way. Since everything is a widget, it's fairly simple to overlay text containing the number over a pin widget.

Let me know if you need more guidance!

**Comment by johnpryan** [comment]
You could take a look at https://github.com/Leaflet/Leaflet.markercluster for inspiration, but the plugin would need to be ported to Dart in order to use it... 

Since this is harder than most contributions, I'll leave this open for anyone that wants to try.

**Comment by zhen1991** [comment]
Hi!
I have a little bit the same problem i wanna add a gruop of marker to my map and i am using flutter map !
any idea about how to do it??
thnx:)

**Comment by etzuk** [comment]
> You could take a look at https://github.com/Leaflet/Leaflet.markercluster for inspiration, but the plugin would need to be ported to Dart in order to use it...
> 
> Since this is harder than most contributions, I'll leave this open for anyone that wants to try.

I need this feature too.

@johnpryan  What do you think about adding MarkerClusterLayer as a layer? (same as marker,circle ...) 
For example:
`class MarkerCluster {
  final List<Marker> markers;
  final WidgetBuilder builder;
  MarkerCluster(this.markers, this.builder);
}`

**Comment by csjames** [comment]
Would users specify their own centroid and markers for each cluster, or
would clustering need to also be handled by the lib?

**Comment by johnpryan** [comment]
I haven't had time to put serious thought into this feature. I would imaging that there would be two builders; one for the case where a pin is not clustered, and one that is clustered (with a number indicating the number of pins) and as @csjames mentioned some way of specifying the cluster distance (e.g. https://www.elastic.co/guide/en/elasticsearch/guide/current/geo-aggs.html)

**Comment by 926** [comment]
Any chance to put this on top ?
Markerclusterer would be a must for our users.
Here is another reference in .js :
**Supercluster** : 

- https://gis.stackexchange.com/questions/261987/custom-icon-for-clusters-in-mapbox-gl-js
- https://www.npmjs.com/package/supercluster

How about reusing : 

- https://github.com/jolleekin/modern_charts/blob/master/lib/src/pie.dart

To get :
![google-map-chart-marker-clusterer](https://github.com/hassanlatif/google-map-chart-marker-clusterer/blob/master/screenshot.png?raw=true)

**Comment by RaimundWege** [comment]
@BramDC3 have a look at #201 in that issue I've described a way how to use k-means with flutter_map and eventually it fits your needs. @926 it should also be possible to use the cluster informations to build up a custom marker like a pie widget.

**Comment by etzuk** [comment]
> I haven't had time to put serious thought into this feature. I imagine that there would be two builders; one for the case where a pin is not clustered, and one that is clustered (with a number indicating the number of pins) and as @csjames mentioned some way of specifying the cluster distance (e.g. https://www.elastic.co/guide/en/elasticsearch/guide/current/geo-aggs.html)

Could you please look at this basic commit? 
https://github.com/etzuk/flutter_map/commit/a4a3c5076c2981b10d932aaecb8e9218cec7a658

Very basic, allow creating a cluster with a list of markers and show on the map as a cluster(basic pin with markers count text or custom widget) or the markers list himself.

**Comment by 926** [comment]
Thanks for sharing  @etzuk 

Also have you looked at :
giandifra’s  [clustering_google_maps](https://github.com/giandifra/clustering_google_maps)
it uses [GEOHASH](https://pub.dartlang.org/packages/geohash) to save the points in local sqflite db.

**Comment by 926** [comment]
Hi all, I keep on receiving demands for a marker/clusterer. So I'm coming back to this issue.

Thank you again @etzuk for providing a customised commit in order to preview the cluster. Below is the screenshot I get : 
![photo_2019-04-15_13-59-35](https://user-images.githubusercontent.com/14161798/56138733-f7410280-5f86-11e9-8d3c-ca26cbe23c87.jpg)

This example does not fragment markers when user zooms in, nor group markers when users zoom out. This is the reason I also mentioned Giandifra's repo which provides zoom in/out functionality. There should be a way to use methods from this repo, I am still trying to debug it...

Regarding the pie widget, @RaimundWege advised to use the cluster information to render custom marker. Indeed this might be the easiest method.  [Charts](https://pub.dartlang.org/packages/charts_flutter) already provides a **gauge** design that could be used.

@BramDC3 do you reckon Leaflet might be willing to sponsor this feature ?

**Comment by etzuk** [comment]
I can continue to develop this feature. I just need to understand if we can agree on the design. 

In my example, MarkersCluster is a layer WDYT about that?
If we agree on that so the next step is solving the logic that shrink/ expands the markers.
Probably in a way that enables developers to inject this logic or take the default that can intersect markers icons or something like that.

Do I miss something?

**Comment by 926** [comment]
Thanks for support !
Raimund already provided a model for the shrink/expand issue :  [#201](https://github.com/johnpryan/flutter_map/issues/)

I think the logic that would empower developers also lies in the pie cluster settings, i.e. how does one configure pies so that they adapt to each case, e.g.  1 - 8 parameters each with custom colours and specific value rendered in gauge or pie chart.

I will work on a mock-up to show how clusters should react as we shrink/expand the map.

**Comment by 926** [comment]
<img width="310" alt="cluster_master" src="https://user-images.githubusercontent.com/14161798/56216548-2623ab00-6051-11e9-9af0-03b56a029219.png">
![cluster_master2](https://user-images.githubusercontent.com/14161798/56216550-2623ab00-6051-11e9-8c7f-b335beca59a5.png)
@etzuk

**Comment by etzuk** [comment]
@926 
Looks great! Could you explain more about the pies and how they splits?
For example, I can understand The cluster of "2" with two colors and "3" with 3 colors but, "3" with 2 colors? 
More than that I really think the best option is to pass a WidgerBuilder as implemented in Markers. It says that the developer can inject his view.

**Comment by 926** [comment]
@etzuk 
Thanks !
Regarding the "3" with two colours, yellow should be a bit bigger.
But the info is that : 

+ 2 are green so presumably ok / available
+ 1 is yellow so average

I have no clue regarding the best option for developer to inject his view. 
I assume this allows to build on top of flutter_map.
Would this also allow is to reuse :  https://pub.dartlang.org/packages/charts_flutter

**Comment by lpongetti** [comment]
https://github.com/lpongetti/flutter_map_marker_cluster

**Comment by 926** [comment]
@lpongetti 
![my man](https://user-images.githubusercontent.com/14161798/59044075-f896f900-886c-11e9-9d83-9bd40b80f85f.gif)

**Comment by lpongetti** [comment]
@926 
if it was helpful put star please! :)

**Comment by MichalMisiaszek** [comment]
The map cluster from lpomgetti does everything what is required.

**Comment by johnpryan** [comment]
Okay - it sounds like we can close this. Thanks @lpongetti!

**Comment by 926** [comment]
Finally managed to launch it on my laptop for a demo.
Seems that the error was due to a combination of bad internet and slow RAM...
Thank you again @lpongetti and @johnpryan 
![Screenshot_20190713-161408](https://user-images.githubusercontent.com/14161798/61173920-156bce00-a589-11e9-8a36-4c2e1e49ee90.jpg)
I will keep you updated if this leads to a dedicated commercial project.
