### ISSUE TITLE
Tilt camera

### ISSUE THREAD

**Issue by mbn18** [johnpryan/flutter_map#220]
Hi,

Is it possible to tilt/pitch the map (camera).
If not, is it technically possible to add such support?

For example in `Mapbox GL` - [link](https://docs.mapbox.com/mapbox-gl-js/example/set-perspective/)
```js
<script>
  mapboxgl.accessToken = '<your access token here>';
  var map = new mapboxgl.Map({
    container: 'map',
    style: 'mapbox://styles/mapbox/streets-v9',
    center: [-73.5804, 45.534830],
    pitch: 60, // pitch in degrees
    bearing: -60, // bearing in degrees
    zoom: 10
  });
</script>
```

or `google_maps_flutter` - [link](https://pub.dartlang.org/packages/google_maps_flutter)
```dart
RaisedButton(
  child: const Text('Go to London'),
  onPressed: mapController == null ? null : () {
    mapController.animateCamera(CameraUpdate.newCameraPosition(
      const CameraPosition(
        bearing: 270.0,
        target: LatLng(51.5160895, -0.1294527),
        tilt: 30.0,
        zoom: 17.0,
      ),
    ));
  },
),
```

**Comment by ibrierley** [comment]
No, that's not possible currently. You could try faking it, but I think there's a few issues off the top of my head.
I'm assuming the example linked, uses vector tiles ? So the characters/locations are independent. You could add some perspective to png tiles, but the lettering wouldn't be ideal, especially if rotated like in a satnav. So I'm guessing vector tiles would be needed.

I note that library uses webgl, which isn't available in flutter currently.

If you add various perspectives, I think the inputs (drags etc) may end up being off, so that would need to be accounted for as well.

So all in all, I assume this wouldn't be a trivial thing to do, unless you just wanted a simple visual none interactive map, then you could look at 3d transforms on tiles and try and hack something together (maybe).

**Comment by mbn18** [comment]
Well, I would like it to be like in Google map app.

![20190204_090551](https://user-images.githubusercontent.com/1744973/52194711-9c3fb080-285d-11e9-86a5-af38a5e1e740.gif)

And an example with sat layer:

![20190204_092103](https://user-images.githubusercontent.com/1744973/52194911-71099100-285e-11e9-893c-ed41cf38924c.gif)

I will try the 3d transforms but I am not sure this is the best way. Maybe a better approach is use some kind of SDK and bridge it?

**Comment by johnpryan** [comment]
yeah, this package might not achieve what you want for this. applying a 3D transform to the tile layer is feasible in Flutter, but requires extra work to determine what tiles to render (there may be tiles in the distance that don't get rendered)
