### ISSUE TITLE
Update cached_network_image dependency to ^0.6.0

### ISSUE THREAD

**Issue by pepie** [johnpryan/flutter_map#234]
Because flutter_map >=0.5.0 depends on cached_network_image ^0.5.1 and [appname] depends on cached_network_image 0.6.0+1, flutter_map >=0.5.0 is forbidden.
So, because [appname] depends on flutter_map 0.5.0, version solving failed

**Comment by pepie** [comment]
Because flutter_map >=0.5.0 depends on cached_network_image ^0.5.1 and [appname] depends on cached_network_image 0.6.0+1, flutter_map >=0.5.0 is forbidden.
So, because [appname] depends on flutter_map 0.5.0, version solving failed.

**Comment by johnpryan** [comment]
That makes sense - are you able to work around the issue using cached_network_image ^0.5.1 in your project?

**Comment by joserocha3** [comment]
@johnpryan  I am having this issue as well. However it is a little more involved. I am using another package that is causing the conflict.

- Basically, `flutter_map` is using `cached_network_image` which uses `flutter_cache_manager`. And `flutter_cache_manager`is using `uuid ^1.0.3`. 

- I am using `graphql_flutter` which uses `uuid ^2.0.0`. So I cannot work around the the issue since I am not directly using `uuid`.

Is there are any plan to soon update `cached_network_image` to the latest version `0.6.2`? It uses `flutter_cache_manager ^0.3.1` which uses `uuid ^2.0.0`.

Thanks!

```
Because flutter_map >=0.5.0 depends on cached_network_image ^0.5.1 which depends on flutter_cache_manager ^0.2.0+1, flutter_map >=0.5.0 requires flutter_cache_manager ^0.2.0+1.
And because flutter_cache_manager >=0.1.2 <=0.3.0-beta.3 depends on uuid ^1.0.3 and graphql_flutter >=1.0.0-beta.1 depends on uuid ^2.0.0, flutter_map >=0.5.0 is incompatible with graphql_flutter >=1.0.0-beta.1.


So, because [appname] depends on both graphql_flutter ^1.0.0-beta.1 and flutter_map ^0.5.0, version solving failed.
pub get failed (1)
exit code 1
```

**Comment by johnpryan** [comment]
Yeah we should be able to publish a version with those updates

**Comment by jesusrp98** [comment]
The `cached_network_image` package has been updated to version `0.7.0` already. Is there anything holding back you to update this package to support the latest version of that package?

**Comment by mulderpf** [comment]
I'll just add to here, also breaking for shared_preferences for me - assume this should fix the entire dependency tree.

`Because no versions of flutter_map match >0.5.0 <0.6.0 and flutter_map 0.5.0 depends on cached_network_image ^0.5.1, flutter_map ^0.5.0 requires cached_network_image ^0.5.1.

And because no versions of cached_network_image match >0.5.1 <0.6.0 and cached_network_image 0.5.1 depends on flutter_cache_manager ^0.2.0+1, flutter_map ^0.5.0 requires flutter_cache_manager ^0.2.0+1.

Because flutter_cache_manager 0.2.0+1 depends on shared_preferences ^0.4.0 and no versions of flutter_cache_manager match >0.2.0+1 <0.3.0, flutter_cache_manager ^0.2.0+1 requires shared_preferences ^0.4.0.

Thus, flutter_map ^0.5.0 requires shared_preferences ^0.4.0.

So, because LondonBusPal depends on both shared_preferences ^0.5.1+1 and flutter_map ^0.5.0, version solving failed.`

**Comment by James-A-White** [comment]
> Because flutter_map >=0.5.0 depends on cached_network_image ^0.5.1 and [appname] depends on cached_network_image 0.6.0+1, flutter_map >=0.5.0 is forbidden.
> So, because [appname] depends on flutter_map 0.5.0, version solving failed

CachedNetworkImage 0.7.0, please.

Also, please be aware, I've found a bug (I think) in the CachedNetworkImage package. If you specify a CircularProgressIndicator as a placeholder, once the image has loaded, the CircularProgressIndicator is not properly unloaded which causes excessive battery drain as the screen continues to update constantly.  If you use placeholders in CachedNetworkImage, please check your performance carefully after implementation.

**Comment by aytunch** [comment]
CachedNetworkImage is widely used and I believe a lot of people are getting this error or soon will. Is there a fix for this?

**Comment by fvisticot** [comment]
same issue, please help us !

**Comment by kunit1** [comment]
Just hit the same issue. Had to downgrade this plugin to the previous version unfortunately. Patiently waiting for the fix.

**Comment by natezhengbne** [comment]
I could not upgrade to 0.5.0 because of 

> Because cached_network_image >=0.5.0+1 <0.6.0-alpha depends on flutter_cache_manager ^0.2.0+1 which depends on shared_preferences ^0.4.0, cached_network_image >=0.5.0+1 <0.6.0-alpha requires shared_preferences ^0.4.0.
And because flutter_map >=0.5.0 depends on cached_network_image ^0.5.1, flutter_map >=0.5.0 requires shared_preferences ^0.4.0.
So, because godesta_app depends on both flutter_map 0.5.0 and shared_preferences 0.5.1+2, version solving failed.
pub get failed (1)

**Comment by mulderpf** [comment]
Hate having to do this, but is there an expected timeline for when this will be updated?  Or how can I do it myself?  I'm unable to upgrade various libaries in my app as per previous comments and unfortunately, I've made myself quite reliant on this library (since it's great and does what I need it to).  If anyone knows how to fix it, could they help?  I am kind of desperate here as I've been stuck for over a month.

Just let me know where to leave the cash.

**Comment by athornz** [comment]
Until the author gets around to updating dependencies, just use my fork:

```
flutter_map:
    git: git@github.com:athornz/flutter_map.git
```

**Comment by aytunch** [comment]
@athornz It says no pubspec.yaml found in repo:(

**Comment by joserocha3** [comment]
@aytunch try

```
flutter_map:
  git:
    url: https://github.com/athornz/flutter_map.git
```
