### ISSUE TITLE
Zoom Levels and Process for Offline Maps

### ISSUE THREAD

**Issue by matyhaty** [johnpryan/flutter_map#386]
When using offline tiles, you obvious get the tiles you want at certain zoom levels.

When using say openstreetmaps online, once you had got to max zoom levels, the pngs of the tiles you have 'scale' up, which keeps the mapping on screen (abit with degraded quality of the images) but allows closer zoom levels, where tiles do not exist.

We would love to impliment this in flutter map - does anyone know how this could be developed, unless it is already a thing?

There are similar issues where people have asked for the same thing to happen inbetween loading of tiles (when you zoom the tile images enlarge until new tiles have loaded in) and thus this could be used when no more offline tiles are found at higher zoom levels

We are developers and happy to help, but will need a bit of direction on this one

Thanks

**Comment by MooNag** [comment]
Is there an issue (I could not find one) for map tiles zooming and scaling until levels of newer layers are loaded in instead of disappearing? I think this would be a good first step towards fixing this issue. When zooming out it is really jarring to have the map suddenly disappear until the next zoom level is loaded in either from an online source or cache.
