### ISSUE TITLE
Rename project

### ISSUE THREAD

**Issue by johnpryan** [johnpryan/flutter_map#4]
Various names have been suggested. Some of the finalists are:

- open_map
- leaflet_map

Feedback is welcome!

**Comment by caioiglesias** [comment]
leaflet_map is more straight to the point

**Comment by saviour123** [comment]
flutter_leaflet

**Comment by avioli** [comment]
My suggestion - leave it as-is.

  - `open_map` does sound like it has something to do with Open Street Map an it has little to do with it (except the tiles url you use in the examples).
  -`leaflet_map` might be interpreted to be endorsed by Leafletjs project - is it? This project is highly influenced by it - sure, but it is not by Vladimir Agafonkin, nor uses any part of Leafletjs, right? `flutter_leaflet` gets the same reasoning.
  - `flutter_map` is to the point - a Flutter plugin, that provides a map widget (and controller). If the Flutter team decides that no package should have "flutter" in its name - then consider renaming it, but since there are more than a hundred packages with "flutter" in their name - such request from the Flutter team is doubtful.

**Comment by johnpryan** [comment]
I think it's probably too late to change the name,  @avioli 's answer makes sense to me
