### ISSUE TITLE
MapBox T&Cs say only their SDKs should be used on mobile

### ISSUE THREAD

**Issue by castaway** [johnpryan/flutter_map#404]
https://www.mapbox.com/legal/tos/ - section 5.1.. Am I misreading that or would it be better not to use mapbox in the examples?

**Comment by johnpryan** [comment]
Here's the response from MapBox:

> Yes, this is a violation of our terms of services section 5.1. As a courtesy, I would highly recommend you change your implementation by October 7th to one of our mobile SDK to prevent your account from suspension per our right under Section 15.2 of the Terms.

We should remove this from the README

**Comment by geisterfurz007** [comment]
I just read through the Mapbox TOS and couldn't find any mention of only their SDK being allowed, however nothing in their changelog on this either. Could someone with legal expertise have a look at this again?

**Comment by castaway** [comment]
> I just read through the Mapbox TOS and couldn't find any mention of only their SDK being allowed, however nothing in their changelog on this either. Could someone with legal expertise have a look at this again?

They moved it - to the [service terms](https://www.mapbox.com/legal/service-terms) - see section 2.1 of the main TOS, and update April 24th, 2020.  Its in the service terms, section 7.1 (Mobile SDKs)

**Comment by geisterfurz007** [comment]
Ah thanks, much appreciated! I completely missed the second ToS 👍

**Comment by aytunch** [comment]
https://github.com/tobrun/flutter-mapbox-gl/issues/641

**Comment by ibrierley** [comment]
For what it's worth, I got a reply r.e Mapbox and my vector tile plugin. It's a little non specific the reply, but it seems to imply I'd be within Mapbox t&c's (as long as I give correct attribution as is normal with 3rd part libraries). So I'm a little confused between that reply and Johns.

**Comment by aytunch** [comment]
@ibrierley look at the above link I provided and the answer from @tobrun the author of the official MapBox plugin:

> @aytunch the mobile SDKs are used under the hood so this requirement should be satisfied.
> Let us know if you have any more questions!

Could you please write the reply you got?

**Comment by ibrierley** [comment]
Sure, there still seems to be a bit of odds with what they imply (when he says "The use case described in this quote seems to be well within our Service") vs the mobile sdk bit though still really, and not sure I can quite square that....

What I suspect is, a package can't necessarily assume they are ok with mapbox, as it depends on how it's used and if mapbox is attributed properly, is it a specific app in the app store etc... I also suspect if you've probably got mapbox labelled properly as they require and it's not a big general solution you'd probably scrape through.

However, they also mention Leaflet.js is ok...is that simply as it's in a browser ? There's obviously a bit of a weird overlap with flutter, eg you can can use flutter in the web etc.

>>>>

Hi there Ian,

Thanks for writing in, and thank you for your patience. We've had a high volume of support tickets recently and I hope I can still be of assistance.

First off, thank you for being conscious of our terms and conditions!

2. Mapping APIs 

2.1. In General. You may only access Map Assets directly through the Mapping APIs. You may cache Map Assets on end-user devices for offline use for up to thirty (30) days, but each device must populate its cache using direct requests to the Mapping APIs and content from a cache may only be consumed by the single end user of the device. On mobile devices, you may only cache up to the limits set in the Mobile SDKs, and you may not circumvent or change those limits. You may not redistribute Map Assets, including from a cache, by proxying, or by using a screenshot or other static image instead of accessing Map Assets through the Mapping APIs.


it's simply decoding your Vector Tiles from your API called by the app, and displaying (bit of my original question they included)


The use case described in this quote seems to be well within our Service [Terms,](https://www.mapbox.com/legal/service-terms) which I would recommend reviewing.

Here is an article from our documentation for attributing third-party libraries:

[Attribution: Other Mapping Frameworks](https://docs.mapbox.com/help/getting-started/attribution/#other-mapping-frameworks)


For faster help with future questions, we recommend checking out our great documentation and guides for more resources including our API Documentation, our help pages, and the Mapbox Stack Overflow community. We encourage you to submit a question on Stack Overflow with the Mapbox tag to take advantage of the large and active community of developers building with Mapbox.

With our Essential, Business, or Premium support plans, we guarantee engagement with our team within a certain time window - check out our Mapbox Support Plans page to learn more.

Regards,

**Comment by aytunch** [comment]
@johnpryan does the response @ibrierley got mean we can put MapBox back to the provider list?
