### ISSUE TITLE
Issues when change map tiles URL dynamically

### ISSUE THREAD

**Issue by jesusrp98** [johnpryan/flutter_map#583]
First thing, congratulation! The v0.9.0 release include really nice features!

Since this new update, when I try to change the map tiles URL while running the app, it takes a couple seconds, after to start navigating the mapo with the finger, until all tiles are updated. Before, this change was instantly performed.

Here's how I change the URL dynamically:
```
FlutterMap(
  mapController: _mapController,
  options: MapOptions(
    ...
  ),
  layers: <LayerOptions>[
    TileLayerOptions(
      urlTemplate: context.watch<MapProvider>().mapUrl,
      backgroundColor: Theme.of(context).canvasColor,
    ),
    MarkerLayerOptions(
      ...
    ),
  ],
),
```

Is this a bug, or is there a better method to update the map URL, for example using the `MapController` class? Thank!

**Comment by maRci002** [comment]
Hello, in #572 PR I implemented Leaflet's tile fetching / retaining strategy. Basicly if a Tile was loaded there is currently no way to force it to change Image based on new url while it is retained.

Give me some time I'll make some changes to watch url changes.

**Comment by jesusrp98** [comment]
Great. This could be implemented as an option inside the `MapController` itself.

For example:
`mapControler.setUrl(newMapUrl);`

Great job, and thanks a lot!

**Comment by maRci002** [comment]
You can test it, just change your dependency and run `flutter pub upgrade`
```
  flutter_map:
    git:
      url: git://github.com/johnpryan/flutter_map.git
      ref: 646912e30075032473b3fce6aea5ab6f2d8b1359
```

You will see the fade in animation (except if you provided `tileFadeInDuration = 0`), if you really need I can provide some flag like `skipTileFadeInWhileReload`, however I think it is unnecessary because even in Leaflet this would be two steps remove old layer and attach new layer which would cause the fade in effect.

**Comment by jesusrp98** [comment]
Works perfectly!
Thank you very much for this fix :)

**Comment by MooNag** [comment]
Using this fix causes flashing (A brief delay where the old image disappears completely, and the new one is not active). if the URL is changed frequently and tileFadeInDuration = 0. I would expect there to be no delay if the fade in is set to zero. The old tile should wait for a new tile to load and swap between them with zero blank time.

**Comment by jesusrp98** [comment]
I have the same problem as @MooNag and I agree that this is an issue @johnpryan

**Comment by maRci002** [comment]
I'll take a look later today.

**Comment by jesusrp98** [comment]
I get what you're saying @maRci002. The thing is that in earlier versions of this plugin, when you change the tile URL, the screen wouldn't flash the background color. It will simply apply all the updated tiles.

So the right behaviour should be just to wait untill all visible tiles are downloaded, and then display the new ones.

You could check this behaviour in `< v0.9.0` version of this package.
Hope I explained it correctly :)

**Comment by MooNag** [comment]
Just to clarify, each tile is loaded individually and replaced individually. @maRci002 @jesusrp98 . The issue is that the tile flashes the background color (transparent) for a brief time when the new one is switched out with this fix. Pre 0.9.0 behavior would be to switch out the tiles instantly without the tile briefly disappearing before the new one appears. This is true even if the fade in delay is set to zero. You can create this by having 2 url layers switch quickly between each other and see the blank frames. It does apply to the whole screen, but individual tiles blank before the new one is shown. When you change the URL, the tile should wait for the new one to load in and then show the new one; but still keep the old tile visible.

**Comment by maRci002** [comment]
I'm pretty sure in `< v0.9.0` version the tiles were independent of each other so it could happen if geoserver delays some tiles download speed because of high triffic then old and new tiles will be shown mixed.

> @MooNag When you change the URL, the tile should wait for the new one to load in and then show the new one; but still keep the old tile visible.
I'll implement this behavior.

**Comment by jesusrp98** [comment]
Nice! Looking forward to test it!

**Comment by maRci002** [comment]
I made some changes to support this kind of behaviour check out:
```
  flutter_map:
    git:
      url: git://github.com/johnpryan/flutter_map.git
      ref: c590ab12edbf5b6fce30b13a42e974c0abadd506
```

First of all set `overrideTilesWhenUrlChanges` to `true` secondly you can you do not have play with `tileFadeInDuration = 0` anymore (feel free to use it) because you can set `tileFadeInStartWhenOverride` to `1.0` to avoid fade in animations when old tile is being override.

I still think `overrideTilesWhenUrlChanges` is an unsafe operation so it is `false` by default, see little demo:
![url change without drop old tiles](https://user-images.githubusercontent.com/8436039/81016996-ccf80680-8e61-11ea-945b-f00ee3ffc0b6.gif)

Please do some tests forinstace what happens if a tile is in loading phase and url changes then new one loads fine and if old finished loading then it should never be on screen (I tested it only in my mind :smile:).

**Comment by MooNag** [comment]
@maRci002 I tested it out. Behaves exactly as intended. There does not seem to be an issue if a tile url is swapped before it is fully loaded It always shows the old one which is preferred. It is exactly as intended! You are insane! This should be a PR as it adds improvements tile fetching behavior.

**Comment by maRci002** [comment]
It is actually a PR see #584 .
